---
- name: Upload Ironic images
  hosts: metalbox
  strategy: linear

  tasks:
    - name: Create ironic-agent-kernel image # noqa: run-once[task]
      delegate_to: localhost
      run_once: true
      openstack.cloud.image:
        cloud: admin
        state: present
        name: ironic-agent-kernel
        container_format: aki
        disk_format: aki
        is_public: true
        filename: /share/ironic/ironic/ironic-agent.kernel

    - name: Create ironic-agent-initramfs image # noqa: run-once[task]
      delegate_to: localhost
      run_once: true
      openstack.cloud.image:
        cloud: admin
        state: present
        name: ironic-agent-initramfs
        container_format: ari
        disk_format: ari
        is_public: true
        filename: /share/ironic/ironic/ironic-agent.initramfs

    - name: Create OSISM node image # noqa: run-once[task]
      delegate_to: localhost
      run_once: true
      openstack.cloud.image:
        cloud: admin
        state: present
        name: osism-node
        container_format: bare
        disk_format: qcow2
        is_public: true
        filename: /share/ironic/ironic/osism.qcow2
