---
##########################################################
# versions

manager_version: latest
openstack_version: 2024.2

##########################################################
# services

enable_ara: false
enable_ceph_ansible: false

##########################################################
# configuration

configuration_git_port: 443
configuration_git_protocol: https
configuration_git_repository: osism/metalbox.git
