---
##########################################################
# versions

manager_version: latest
openstack_version: 2024.2

##########################################################
# services

enable_ceph_ansible: false
enable_osism_kubernetes: false
enable_vault: false

##########################################################
# api

osism_api_host: 192.168.42.10

##########################################################
# ara-server

ara_server_host: 192.168.42.10

##########################################################
# listener

manager_listener_broker_hosts:
  - 192.168.42.10
manager_listener_broker_username: openstack
manager_listener_broker_uri: "{% for host in manager_listener_broker_hosts %}amqp://{{ manager_listener_broker_username }}:{{ manager_listener_broker_password }}@{{ host }}:5672/{% if not loop.last %};{% endif %}{% endfor %}"

##########################################################
# manager

manager_service_manual_start: true
manager_service_allow_restart: false

##########################################################
# watchdog

manager_enable_watchdog: false

##########################################################
# openstack

manager_openstack_os_project_domain_name: Default
manager_openstack_os_user_domain_name: Default
manager_openstack_os_project_name: admin
manager_openstack_os_username: admin
manager_openstack_os_auth_url: http://api.metalbox.osism.xyz:5000/v3

##########################################################
# netbox

netbox_enable: true
netbox_host: 0.0.0.0
netbox_service_netbox_start_period: 300s
netbox_service_allow_restart: false
netbox_api_url: "http://192.168.42.10:8121"

netbox_filter_conductor_ironic:
  - state: active
    site: Discworld
    tag:
      - managed-by-ironic
netbox_filter_conductor_sonic:
  - state: active
    site: Discworld
    tag:
      - managed-by-metalbox
netbox_filter_inventory:
  - state: active
    site: Discworld
    tag:
      - managed-by-osism
netbox_role_mapping: {}
netbox_data_types:
  - dnsmasq_parameters
  - frr_parameters
  - gnmic_parameters
  - netplan_parameters
  - primary_ip

manager_inventory_from_netbox: true
manager_inventory_reconciler_mode: metalbox

##########################################################
# schedules

manager_inventory_reconciler_schedule: 0
manager_gather_facts_schedule: 0

##########################################################
# configuration

configuration_git_version: main

configuration_git_port: 443
configuration_git_protocol: https
configuration_git_repository: osism/metalbox.git
