---
##########################################################
# versions

manager_version: latest
openstack_version: 2024.2

##########################################################
# services

enable_ara: false
enable_ceph_ansible: false
enable_osism_kubernetes: false
enable_vault: false

##########################################################
# configuration

configuration_git_version: main

configuration_git_port: 443
configuration_git_protocol: https
configuration_git_repository: osism/metalbox.git
