DEVICETYPE_LIBRARY = "devicetypes"
IGNORE_SSL_ERRORS = true
MODULETYPE_LIBRARY = "moduletypes"
RESOURCES = "resources"
URL = "http://192.168.42.10:8121"
VERBOSE = true
TOKEN = "0000000000000000000000000000000000000000"
