---
# docker
docker_opts:
  max-concurrent-downloads: 20
# renovate: datasource=github-releases depName=moby/moby
docker_version: '5:27.5.1'
docker_facts: false
docker_insecure_registries:
  - localhost:5000

# hosts
hosts_type: template
hosts_additional_entries:
  api.metalbox.osism.xyz: 192.168.42.10
