---
# chrony
chrony_bind_local_interfaces_only: false
chrony_allowed_subnets:
  - 10/8
  - 127.0.0.1/32
  - 172.16/12
  - 192.168/16

# docker
docker_opts:
  max-concurrent-downloads: 20
# renovate: datasource=github-releases depName=moby/moby
docker_version: '5:27.5.1'
docker_facts: false
docker_insecure_registries:
  - localhost:5000

# hosts
hosts_type: template
hosts_group_name: none
hosts_additional_entries:
  api.metalbox.osism.xyz: 192.168.42.10
  metalbox: 192.168.42.10

# network
network_allow_service_restart: true

# operator
operator_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIquLz7xZ1rzpsoivjOiZTarg+jri0ezRn823wGw4G0gFfosxPxNJ4BS1LaGjje9YI4JVsU2btDuxcNIvmRehVLPHxRwpDHE+FVajltnF1DQXiySitdbC27N1NIaVbWv8y1C2PFnXL+QUrF2VddOzNnMBXingEV2Ev/bTW/XfVTTArpHsNTS0DJRMpMeUROHmCwxhWjjuFfCcH2EEn5KyBCvgiQIozkwf5Q7nK3DeG2QODxtLPJkmCEuvpqbwZF8VkaE1n1TLr7a9CD/p4sn1+Z1BJO+Zsg72AM9A0lKQ0/1TCsAHLMIoZoNH2F7JeNtApFhDAEg9EZGyk0RDkrKxojYzuimvoyYXI84JDdKx3kDFGiXB3ITDMOFRajGLdgJwAZT2Aw62H0uWQs1dMNRtMgaemLIDmschZDVH5j9iDwEZaKVzJ6LLDSn1Wl09nuZNV8okNIvsBe4X6mHzqwLOYYga/HmI6y4nudTLSeckFraMXGRFFfGHDVpNwKRRavx0= dragon@osism
operator_environment:
  PATH: "$PATH:/opt/configuration/scripts"
