---
##########################################################
# dnsmasq

dnsmasq_enable_dns: true
dnsmasq_dhcp_options:
  - tag:edgecore,114,http://metalbox/sonic/sonic-broadcom-enterprise-base-4.4.2.bin

##########################################################
# httpd

httpd_host: 0.0.0.0
httpd_port: 80

##########################################################
# netbox

netbox_host: 192.168.42.10
netbox_service_netbox_start_period: 300s
