---
##########################################################
# dnsmasq

dnsmasq_dhcp_options:
  - tag:edgecore,114,http://192.168.42.10/sonic/sonic-broadcom-enterprise-base-4.4.2.bin

##########################################################
# httpd

httpd_host: 192.168.42.10
httpd_port: 80

##########################################################
# netbox

netbox_host: 192.168.42.10
netbox_service_netbox_start_period: 300s
