---
- name: Mirror debian packages
  hosts: all

  vars:
    _publish: "{{ publish | default(False) }}"
    docker_registry: quay.io
    s3_endpoint: https://nbg1.your-objectstorage.com

  tasks:
    - name: Run mirror script
      become: true
      ansible.builtin.shell:  # noqa command-instead-of-module
        executable: /bin/bash
        cmd: "{{ lookup('file', 'files/create-mirror.sh') }}"
      environment:
        SCRIPT_DIR: "{{ zuul.project.src_dir }}/zuul/files"
      changed_when: true

    - name: Log into registry
      community.docker.docker_login:
        registry_url: "{{ docker_registry }}"
        username: "{{ secret.DOCKER_USERNAME }}"
        password: "{{ secret.DOCKER_PASSWORD }}"
      when: _publish | default(false) | bool
      no_log: true

    - name: Prepare export archive
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          version=$(date +%Y%m%d)
          docker tag "quay.io/osism-mirror/ubuntu-noble:$version" registry.osism.tech/osism/packages/ubuntu-noble:latest
          docker save registry.osism.tech/osism/packages/ubuntu-noble:latest | bzip2 > ubuntu-noble.tar.bz2
          sha256sum ubuntu-noble.tar.bz2 > ubuntu-noble.tar.bz2.CHECKSUM
      when: _publish | default(false) | bool
      changed_when: true


    - name: Install rclone
      become: true
      ansible.builtin.apt:
        name: rclone
        state: present
        update_cache: true
      when: _publish | default(false) | bool

    - name: Run push and upload script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          version=$(date +%Y%m%d)
          docker push "quay.io/osism-mirror/ubuntu-noble:$version"

          rclone copyto ubuntu-noble.tar.bz2.CHECKSUM s3:osism/metalbox/ubuntu-noble.tar.bz2.CHECKSUM
          rclone copyto ubuntu-noble.tar.bz2 s3:osism/metalbox/ubuntu-noble.tar.bz2
      environment:
        RCLONE_CONFIG_S3_TYPE: s3
        RCLONE_CONFIG_S3_PROVIDER: Ceph
        RCLONE_CONFIG_S3_ENDPOINT: "{{ s3_endpoint }}"
        RCLONE_CONFIG_S3_ACCESS_KEY_ID: "{{ secret.ACCESS_KEY | trim }}"
        RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "{{ secret.SECRET_KEY | trim }}"
        RCLONE_CONFIG_S3_ACL: public-read
      when: _publish | default(false) | bool
      changed_when: true
      no_log: true
