---
- name: Mirror octavia image
  hosts: all

  vars:
    _openstack_versions: "{{ openstack_versions | default(['2024.2', '2025.1']) }}"
    _publish: "{{ publish | default(False) }}"

  tasks:
    - name: Run export script for {{ item }}
      become: true
      ansible.builtin.shell:  # noqa command-instead-of-module
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          bash scripts/octavia-export.sh {{ item }}
      changed_when: true
      loop: "{{ _openstack_versions }}"

    - name: Install rclone
      become: true
      ansible.builtin.apt:
        name: rclone
        state: present
        update_cache: true
      when: _publish | default(false) | bool

    - name: Run upload for {{ item }}
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          sha256sum octavia-export-{{ item }}.img > octavia-export-{{ item }}.img.CHECKSUM

          rclone copyto octavia-export-{{ item }}.img.CHECKSUM s3:osism/metalbox/octavia-export-{{ item }}.img.CHECKSUM
          rclone copyto octavia-export-{{ item }}.img s3:osism/metalbox/octavia-export-{{ item }}.img
      environment:
        RCLONE_CONFIG_S3_TYPE: s3
        RCLONE_CONFIG_S3_PROVIDER: Ceph
        RCLONE_CONFIG_S3_ENDPOINT: https://nbg1.your-objectstorage.com
        RCLONE_CONFIG_S3_REGION: nbg1
        RCLONE_CONFIG_S3_ACCESS_KEY_ID: "{{ secret.ACCESS_KEY | trim }}"
        RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "{{ secret.SECRET_KEY | trim }}"
        RCLONE_CONFIG_S3_ACL: public-read
        RCLONE_CONFIG_S3_NO_CHECK_BUCKET: "true"
      when: _publish | default(false) | bool
      changed_when: true
      no_log: true
      loop: "{{ _openstack_versions }}"
