---
- name: Mirror octavia image
  hosts: all

  vars:
    _openstack_version: "{{ openstack_version | default('2024.2') }}"
    _publish: "{{ publish | default(False) }}"
    minio_url: https://nbg1.your-objectstorage.com

  tasks:
    - name: Run export script
      become: true
      ansible.builtin.shell:  # noqa command-instead-of-module
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          bash scripts/octavia-export.sh {{ _openstack_version }}
      changed_when: true

    - name: Run push and upload script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          sha256sum octavia-export-{{ _openstack_version }}.img > octavia-export-{{ _openstack_version }}.img.CHECKSUM

          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set minio {{ minio_url }} {{ secret.MINIO_ACCESS_KEY | trim }} {{ secret.MINIO_SECRET_KEY | trim }}
          ./mc cp octavia-export-{{ _openstack_version }}.img.CHECKSUM minio/osism/metalbox/
          ./mc cp octavia-export-{{ _openstack_version }}.img minio/osism/metalbox/
      when: _publish | default(false) | bool
      changed_when: true
      no_log: true
