---
- name: Mirror debian packages
  hosts: all

  vars:
    _publish: "{{ publish | default(False) }}"

  tasks:
    - name: Run mirror script
      become: true
      ansible.builtin.shell:  # noqa command-instead-of-module
        executable: /bin/bash
        cmd: "{{ lookup('file', 'files/create-mirror.sh') }}"
      environment:
        SCRIPT_DIR: "{{ zuul.project.src_dir }}/zuul/files"
      changed_when: true

    - name: Run push script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          version=$(date +%Y%m%d)
          docker push "quay.io/osism-packages/ubuntu-noble:$version"
      when: _publish | default(false) | bool
      changed_when: true
