---
- name: Mirror octavia image
  hosts: all

  vars:
    _openstack_version: "{{ openstack_version | default('2024.2') }}"
    _publish: "{{ publish | default(False) }}"
    s3_endpoint: https://nbg1.your-objectstorage.com

  tasks:
    - name: Run export script
      become: true
      ansible.builtin.shell:  # noqa command-instead-of-module
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          bash scripts/octavia-export.sh {{ _openstack_version }}
      changed_when: true

    - name: Install rclone
      become: true
      ansible.builtin.apt:
        name: rclone
        state: present
        update_cache: true
      when: _publish | default(false) | bool

    - name: Run upload
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir | default('.') }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          sha256sum octavia-export-{{ _openstack_version }}.img > octavia-export-{{ _openstack_version }}.img.CHECKSUM

          rclone copyto octavia-export-{{ _openstack_version }}.img.CHECKSUM s3:osism/metalbox/octavia-export-{{ _openstack_version }}.img.CHECKSUM
          rclone copyto octavia-export-{{ _openstack_version }}.img s3:osism/metalbox/octavia-export-{{ _openstack_version }}.img
      environment:
        RCLONE_CONFIG_S3_TYPE: s3
        RCLONE_CONFIG_S3_PROVIDER: Other
        RCLONE_CONFIG_S3_ENDPOINT: "{{ s3_endpoint }}"
        RCLONE_CONFIG_S3_ACCESS_KEY_ID: "{{ secret.ACCESS_KEY | trim }}"
        RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "{{ secret.SECRET_KEY | trim }}"
      when: _publish | default(false) | bool
      changed_when: true
      no_log: true
