---
- name: Mirror container images
  hosts: all

  vars_files:
    - vars/container-images.yml

  vars:
    docker_registry: registry.osism.tech
    s3_endpoint: https://nbg1.your-objectstorage.com
    _publish: "{{ publish | default(False) }}"
    _full: "{{ full | default(False) }}"

  tasks:
    - name: Create registry volume
      community.docker.docker_volume:
        name: registry

    - name: Run local container registry
      community.docker.docker_container:
        name: registry
        image: registry:3
        state: started
        ports:
          - "5000:5000"
        volumes:
          - registry:/var/lib/registry

    - name: Copy images
      ansible.builtin.command:
        cmd: "skopeo copy --retry-times 2 --dest-tls-verify=false docker://{{ docker_registry }}/dockerhub/{{ item }} docker://localhost:5000/{{ item }}"
      loop: "{{ images }}"
      changed_when: false

    - name: Copy manager images
      ansible.builtin.command:
        cmd: "skopeo copy --retry-times 2 --dest-tls-verify=false docker://{{ docker_registry }}/osism/{{ item }} docker://localhost:5000/osism/{{ item }}"
      loop: "{{ images_manager }}"
      changed_when: false

    - name: Copy kolla images
      ansible.builtin.command:
        cmd: "skopeo copy --retry-times 2 --dest-tls-verify=false docker://{{ docker_registry }}/kolla/{{ item }} docker://localhost:5000/kolla/{{ item }}"
      loop: "{{ images_kolla_metalbox }}"
      changed_when: false

    - name: Copy remaining kolla images
      ansible.builtin.command:
        cmd: "skopeo copy --retry-times 2 --dest-tls-verify=false docker://{{ docker_registry }}/kolla/{{ item }} docker://localhost:5000/kolla/{{ item }}"
      loop: "{{ images_kolla }}"
      changed_when: false
      when: _full | bool

    - name: Stop local container registry
      community.docker.docker_container:
        name: registry
        state: stopped
      when: _publish | bool

    - name: Run export container
      community.docker.docker_container:
        name: export
        image: alpine
        state: started
        command: sh -c 'sleep infinity'
        volumes:
          - registry:/volume
          - "./:/export"
      when: _publish | bool

    - name: Export registry volume
      community.docker.docker_container_exec:
        container: export
        command: sh -c 'cd /volume && tar cjf /export/registry.tar.bz2 .'
      when: _publish | bool

    - name: Get size of export archive
      ansible.builtin.stat:
        path: registry.tar.bz2
      register: result
      when: _publish | bool

    - name: Print size of export archive
      ansible.builtin.debug:
        msg: "{{ (result.stat.size / (1024 * 1024)) | round(2) }} MB"
      when:
        - _publish | bool
        - result.stat.exists

    - name: Install rclone
      become: true
      ansible.builtin.apt:
        name: rclone
        state: present
        update_cache: true
      when: _publish | bool

    - name: Run upload (metalbox)
      ansible.builtin.shell:  # noqa command-instead-of-module
        executable: /bin/bash
        cmd: |
          sha256sum registry.tar.bz2 > registry.tar.bz2.CHECKSUM
          rclone copyto registry.tar.bz2.CHECKSUM s3:osism/metalbox/registry.tar.bz2.CHECKSUM
          rclone copyto registry.tar.bz2 s3:osism/metalbox/registry.tar.bz2
      environment:
        RCLONE_CONFIG_S3_TYPE: s3
        RCLONE_CONFIG_S3_PROVIDER: Other
        RCLONE_CONFIG_S3_ENDPOINT: "{{ s3_endpoint }}"
        RCLONE_CONFIG_S3_ACCESS_KEY_ID: "{{ secret.ACCESS_KEY | trim }}"
        RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "{{ secret.SECRET_KEY | trim }}"
      when:
        - not _full | bool
        - _publish | bool
      no_log: true
      changed_when: true

    - name: Run upload (full)
      ansible.builtin.shell:  # noqa command-instead-of-module
        executable: /bin/bash
        cmd: |
          mv registry.tar.bz2 registry-full.tar.bz2
          sha256sum registry-full.tar.bz2 > registry-full.tar.bz2.CHECKSUM
          rclone copyto registry-full.tar.bz2.CHECKSUM s3:osism/metalbox/registry-full.tar.bz2.CHECKSUM
          rclone copyto registry-full.tar.bz2 s3:osism/metalbox/registry-full.tar.bz2
      environment:
        RCLONE_CONFIG_S3_TYPE: s3
        RCLONE_CONFIG_S3_PROVIDER: Other
        RCLONE_CONFIG_S3_ENDPOINT: "{{ s3_endpoint }}"
        RCLONE_CONFIG_S3_ACCESS_KEY_ID: "{{ secret.ACCESS_KEY | trim }}"
        RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "{{ secret.SECRET_KEY | trim }}"
      when:
        - _full | bool
        - _publish | bool
      no_log: true
      changed_when: true
