---
network_ethernets:
  eth*:
    dhcp4: no
    dhcp6: no
    link-local: [ipv6]
  en*:
    dhcp4: no
    dhcp6: no
    link-local: [ipv6]
  enp*:
    dhcp4: no
    dhcp6: no
    link-local: [ipv6]
  eno*:
    dhcp4: no
    dhcp6: no
    link-local: [ipv6]

network_dummy_devices:
  metalbox:
    addresses:
      - 192.168.42.10/24
