---
docker_namespace: kolla

kolla_internal_vip_address: 192.168.42.10
kolla_internal_fqdn: api.metalbox.osism.xyz

kolla_enable_tls_internal: "no"
kolla_enable_tls_external: "no"

openstack_service_workers: 2

enable_cinder: "no"
enable_fluentd: "no"
enable_horizon: "no"
enable_ironic: "yes"
enable_keepalived: "no"
enable_neutron: "no"
enable_nova: "no"
enable_proxysql: "no"

om_enable_rabbitmq_high_availability: false
om_enable_rabbitmq_quorum_queues: false

enable_ironic_agent_download_images: false

ironic_http_url: "http://metalbox/ironic"

enable_ironic_prometheus_exporter: false
enable_prometheus_alertmanager: false
enable_prometheus_blackbox_exporter: false
enable_prometheus_cadvisor: false
enable_prometheus_ceph_mgr_exporter: false
enable_prometheus_elasticsearch_exporter: false
enable_prometheus_haproxy_exporter: false
enable_prometheus_libvirt_exporter: false
enable_prometheus_memcached_exporter: false
enable_prometheus_mysqld_exporter: false
enable_prometheus_node_exporter: false
enable_prometheus_openstack_exporter: false
enable_prometheus_openstack_exporter_external: false
enable_prometheus_proxysql_exporter: false
enable_prometheus_rabbitmq_exporter: false

prometheus_cmdline_extras: "--web.enable-remote-write-receiver"
