---
docker_namespace: kolla

kolla_internal_vip_address: 192.168.42.10
kolla_internal_fqdn: api.metalbox.osism.xyz

kolla_enable_tls_internal: "no"
kolla_enable_tls_external: "no"

openstack_service_workers: 2

enable_cinder: "no"
enable_fluentd: "no"
enable_glance: "no"
enable_horizon: "no"
enable_ironic: "yes"
enable_keepalived: "no"
enable_neutron: "no"
enable_nova: "no"
enable_proxysql: "no"

om_enable_rabbitmq_high_availability: false
om_enable_rabbitmq_quorum_queues: false

enable_ironic_agent_download_images: false
