---
docker_namespace: kolla

kolla_internal_vip_address: 192.168.42.10
kolla_internal_fqdn: api.metalbox.osism.xyz
kolla_enable_tls_internal: "no"

openstack_service_workers: 2

enable_ironic: "yes"

om_enable_rabbitmq_high_availability: false
om_enable_rabbitmq_quorum_queues: false
