---
gnmic_outputs:
  prometheus:
    type: prometheus_write
    url: http://metalbox:9091/api/v1/write
    metadata:
      include: true
    authentication:
      username: admin
      password: password
